#version 460

#include "core/struct.glsl"

layout(local_size_x = 32) in;

layout (set = 0, binding = 0) buffer writeonly DrawCommandBuffer {
  VkDrawIndexedIndirectCommand drawCommands[];
};

void main() {
  VkDrawIndexedIndirectCommand drawCommand;
  drawCommand.indexCount = 0u;
  drawCommand.instanceCount = 0u;    
  drawCommand.vertexOffset = 0;
  drawCommand.firstInstance = 0u;
  drawCommand.firstIndex = 0u;

  drawCommands[gl_GlobalInvocationID.x] = drawCommand;
}