#pragma once

enum ImageUsage
{
    TRANSFER_SRC,
    TRANSFER_DST,
    SAMPLED,
    STORAGE,
    COLOR_ATTACHMENT,
    DEPTH_STENCIL_ATTACHMENT,
    TRANSIENT_ATTACHMENT,
    INPUT_ATTACHMENT
};

enum BufferUsage
{
    TRANSFER_SRC,
    TRANSFER_DST,
    UNIFORM_TEXEL,
    STORAGE_TEXEL,
    UNIFORM,
    STORAGE,
    INDEX,
    VERTEX,
    INDIRECT
};

enum ImageLayout
{
    UNDEFINED,
    GENERAL,
    COLOR_ATTACHMENT_OPTIMAL,
    DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
    DEPTH_STENCIL_READ_ONLY_OPTIMAL,
    SHADER_READ_ONLY_OPTIMAL,
    TRANSFER_SRC_OPTIMAL,
    TRANSFER_DST_OPTIMAL,
    PREINITIALIZED
};

enum ImageTiling
{
    OPTIMAL,
    LINEAR,
};

enum Filter 
{
    NEAREST,
    LINEAR
};

enum SamplerMipmapMode
{
    NEAREST,
    LINEAR
};

enum SamplerAddressMode
{
    REPEAT,
    MIRRORED_REPEAT,
    CLAMP_TO_EDGE,
    CLAMP_TO_BORDER
};

enum CompareOp
{
    NEVER,
    LESS,
    EQUAL,
    LESS_OR_EQUAL,
    GREATER,
    NOT_EQUAL,
    GREATER_OR_EQUAL,
    ALWAYS
};

enum DescriptorType
{
    SAMPLER,
    COMBINED_IMAGE_SAMPLER,
    SAMPLED_IMAGE,
    STORAGE_IMAGE,
    UNIFORM_TEXEL_BUFFER,
    STORAGE_TEXEL_BUFFER,
    UNIFORM_BUFFER,
    STORAGE_BUFFER,
    UNIFORM_BUFFER_DYNAMIC,
    STORAGE_BUFFER_DYNAMIC,
    INPUT_ATTACHMENT
};

enum PipelineStage 
{
    TOP_OF_PIPE,
    DRAW_INDIRECT,
    VERTEX_INPUT,
    VERTEX_SHADER,
    TESSELLATION_CONTROL_SHADER,
    TESSELLATION_EVALUATION_SHADER,
    GEOMETRY_SHADER0,
    FRAGMENT_SHADER0,
    EARLY_FRAGMENT_TESTS,
    LATE_FRAGMENT_TESTS,
    COLOR_ATTACHMENT_OUTPUT,
    COMPUTE_SHADER,
    TRANSFER,
    BOTTOM_OF_PIPE,
    HOST,
    ALL_GRAPHICS,
    ALL_COMMANDS
};

enum ShaderStage
{
    VERTEX,
    TESSELLATION_CONTROL,
    TESSELLATION_EVALUATION,
    GEOMETRY,
    FRAGMENT,
    COMPUTE,

    RAYGEN,
    ANY_HIT,
    CLOSEST_HIT,
    MISS,
    INTERSECTION,
    CALLABLE,
    TASK,
    MESH,

    ALL_GRAPHICS,
    ALL,
};

enum Access
{
    INDIRECT_COMMAND_READ,
    INDEX_READ,
    VERTEX_ATTRIBUTE_READ,
    UNIFORM_READ,
    INPUT_ATTACHMENT_READ,
    SHADER_READ,
    SHADER_WRITE,
    COLOR_ATTACHMENT_READ,
    COLOR_ATTACHMENT_WRITE,
    DEPTH_STENCIL_ATTACHMENT_READ,
    DEPTH_STENCIL_ATTACHMENT_WRITE,
    TRANSFER_READ,
    TRANSFER_WRITE,
    HOST_READ,
    HOST_WRITE,
    MEMORY_READ,
    MEMORY_WRITE
};

enum Format
{
    UNDEFINED,

    R32_SFLOAT,
    R32G32_SFLOAT,
    R32G32B32_SFLOAT,
    R32G32B32A32_SFLOAT,

    R32_UINT,
    R32G32_UINT,
    R32G32B32_UINT,
    R32G32B32A32_UINT,

    R8G8B8A8_SRGB
};

enum AttachmentLoadOp
{
    LOAD,
    CLEAR,
    DONT_CARE
};

enum AttachmentStoreOp
{
    STORE,
    DONT_CARE
};

enum ColorSpace
{
    SRGB_NONLINEAR
};

enum PresentMode
{
    IMMEDIATE = 0,
    MAILBOX = 1,
    FIFO = 2,
    FIFO_RELAXED = 3
};

enum SurfaceTransform
{
    IDENTITY,
    ROTATE_90,
    ROTATE_180,
    ROTATE_270,
    HORIZONTAL_MIRROR,
    HORIZONTAL_MIRROR_ROTATE_90,
    HORIZONTAL_MIRROR_ROTATE_180,
    HORIZONTAL_MIRROR_ROTATE_270,
    INHERIT
};

enum CompositeAlpha
{
    OPAQUE,
    PRE_MULTIPLIED,
    POST_MULTIPLIED,
    INHERIT
};

enum BorderColor
{
    FLOAT_TRANSPARENT_BLACK,
    INT_TRANSPARENT_BLACK,
    FLOAT_OPAQUE_BLACK,
    INT_OPAQUE_BLACK,
    FLOAT_OPAQUE_WHITE,
    INT_OPAQUE_WHITE
};

